// <auto-generated />
using System;
using EntityFrameworkApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFrameworkApp.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200227061250_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityFrameworkApp.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<int?>("painterId")
                        .HasColumnType("int");

                    b.Property<int?>("setId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("painterId");

                    b.HasIndex("setId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("EntityFrameworkApp.Painter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Painters");
                });

            modelBuilder.Entity("EntityFrameworkApp.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseDate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("EntityFrameworkApp.Card", b =>
                {
                    b.HasOne("EntityFrameworkApp.Painter", "painter")
                        .WithMany()
                        .HasForeignKey("painterId");

                    b.HasOne("EntityFrameworkApp.Set", "set")
                        .WithMany()
                        .HasForeignKey("setId");
                });
#pragma warning restore 612, 618
        }
    }
}
